config/routes.rb
Tapp01::Application.routes.draw do

	get "menuitems/index_tbody"
  resources :menuitems

  resources :releases

  match "names/absorb", :controller => :names, :action => :absorb
  match "names/delete_all", :controller => :names, :action => :delete_all
  match "names/export", :controller => :names, :action => :export, :via => :get
  match "names/import", :controller => :names, :action => :import

  resources :names

  resources :preferences

  get  "store/absorb_names"
  get  "store/check"
  get  "store/index"
  get  "store/new"
  get  "store/edit"
  match 'store/edit/:id', :controller => :store, :action => :edit
  post "store/cancel_order"
  post "store/deliver_order"
  post "store/save_order"
  get  "store/seimei"
  get  "store/show"
  match 'store/show/:id', :controller => :store, :action => :show
  get  "store/summary"
  get  "store/summary_table_by_date"

  resources :line_items

  resources :orders

  resources :products

  resources :titles

end

app/models/name.rb
# coding: utf-8
# vim:sw=2:ts=2
class Name < ActiveRecord::Base

  def self.from_string(str)
    f = str.split("　")
    if f.length == 2
      name = self.new(sei: f[0], mei: f[1] )
    else
      name = self.new(sei: str, mei: "" )
    end
    name
  end

end

app/controllers/names_controller.rb
# coding: utf-8
# vim:sw=2:ts=2
class NamesController < ApplicationController
  # GET /names
  # GET /names.json
  def index
		if params[:all]
    	@names = Name.all
		else
			@names = Name.where(["mei = ''"]).order('id DESC')
		end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @names }
    end
  end

  # GET /names/1
  # GET /names/1.json
  def show
    @name = Name.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @name }
    end
  end

  # GET /names/new
  # GET /names/new.json
  def new
    @name = Name.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @name }
    end
  end

  # GET /names/1/edit
  def edit
    @name = Name.find(params[:id])
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(params[:name])

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render json: @name, status: :created, location: @name }
      else
        format.html { render action: "new" }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /names/1
  # PUT /names/1.json
  def update
    @name = Name.find(params[:id])

		if params[:index]
			n = @name.sei.length
			i = params[:index].to_i
			if i < n
				params[:name][:mei] = params[:name][:sei][i .. n]
				params[:name][:sei] = params[:name][:sei][0 .. i-1]
			end
		end

    respond_to do |format|
      if @name.update_attributes(params[:name])
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

	# DELETE /names/1
	# DELETE /names/1.json
	def destroy
		@name = Name.find(params[:id])
		@name.destroy

		respond_to do |format|
			format.html { redirect_to names_url }
			format.json { head :ok }
		end
	end

	# PUT /names/absorb
	def absorb

		for order in Order.all
			f = order.name.split("　")
			if f.length == 2
				name = Name.new(:sei => f[0], :mei => f[1] )
			else
				name = Name.new(:sei => order.name, :mei => "" )
			end
			name.save
		end

		respond_to do |format|
			format.html { redirect_to :action => :index }
		end
	end

	# DELETE
	def delete_all

		Name.delete_all

		respond_to do |format|
			format.html { redirect_to :action => :index }
		end
	end

	# GET /names/export
	# GET /names/export.json
	def export

		name_list = []
		for name in Name.all
			name_list << [name.sei, name.mei ]
		end

		File.open('tmp/names.yml', 'w') {|f|
			f.write YAML.dump(name_list)
		}

		respond_to do |format|
			format.html { redirect_to :action => :index }
			format.json { render json: @orders }
		end
	end

	# PUT /names/import
	# PUT /names/import.json
	def import

		name_list = []
		File.open('tmp/names.yml', 'r') {|f|
			name_list = YAML.load(f.read)
		}

		for seimei in name_list
			name = Name.new(:sei => seimei[0], :mei => seimei[1] )
			name.save
		end

		respond_to do |format|
			format.html { redirect_to :action => :index }
			format.json { render json: @orders }
		end
	end

end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/names/_form.html.erb
<%= form_for(@name) do |f| %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sei %><br />
    <%= f.text_field :sei %>
  </div>
  <% if @name.sei != '' and @name.mei == '' %>
  <div >
  <% i = 0 %>
  <% @name.sei.each_char {|c| %>
  	<%= c -%>
	<%= radio_button_tag 'index', i+=1 -%>
  <% } %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :mei %><br />
    <%= f.text_field :mei %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render 'form' %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

app/views/names/index.html.erb
<h1>姓名の一覧</h1>

<%= link_to '追加', new_name_path %>

<%= link_to '取り込み', :controller => 'names', :action => :absorb %>

<%= link_to '書き出し', :controller => 'names', :action => :export %>

<%= link_to '読み込み', :controller => 'names', :action => :import %>

<%= link_to '全て削除', :controller => 'names', :action => :delete_all %>

<table class="names" >
  <tr>
    <th>姓</th>
    <th>名</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @names.each do |name| %>
  <tr>
    <td><%= name.sei %></td>
    <td><%= name.mei %></td>
    <td class="link" ><%= link_to '表示', name %></td>
    <td class="link" ><%= link_to '編集', edit_name_path(name) %></td>
    <td class="link" ><%= link_to '削除', name, confirm: '本当に削除してよろしいですか？', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '追加', new_name_path %>

app/views/names/new.html.erb
<h1>New name</h1>

<%= render 'form' %>

<%= link_to 'Back', names_path %>

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sei:</b>
  <%= @name.sei %>
</p>

<p>
  <b>Mei:</b>
  <%= @name.mei %>
</p>


<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>