config/routes.rb
Tapp01::Application.routes.draw do

	get "menuitems/index_tbody"
  resources :menuitems

  resources :releases

  match "names/absorb", :controller => :names, :action => :absorb
  match "names/delete_all", :controller => :names, :action => :delete_all
  match "names/export", :controller => :names, :action => :export, :via => :get
  match "names/import", :controller => :names, :action => :import

  resources :names

  resources :preferences

  get  "store/absorb_names"
  get  "store/check"
  get  "store/index"
  get  "store/new"
  get  "store/edit"
  match 'store/edit/:id', :controller => :store, :action => :edit
  post "store/cancel_order"
  post "store/deliver_order"
  post "store/save_order"
  get  "store/seimei"
  get  "store/show"
  match 'store/show/:id', :controller => :store, :action => :show
  get  "store/summary"
  get  "store/summary_table_by_date"

  resources :line_items

  resources :orders

  resources :products

  resources :titles

end

app/models/preference.rb
class Preference < ActiveRecord::Base
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @preferences }
    end
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
    @preference = Preference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @preference }
    end
  end

  # GET /preferences/new
  # GET /preferences/new.json
  def new
    @preference = Preference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @preference }
    end
  end

  # GET /preferences/1/edit
  def edit
    @preference = Preference.find(params[:id])
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(params[:preference])

    respond_to do |format|
      if @preference.save
        format.html { redirect_to @preference, notice: 'Preference was successfully created.' }
        format.json { render json: @preference, status: :created, location: @preference }
      else
        format.html { render action: "new" }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /preferences/1
  # PUT /preferences/1.json
  def update
    @preference = Preference.find(params[:id])

    respond_to do |format|
      if @preference.update_attributes(params[:preference])
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference = Preference.find(params[:id])
    @preference.destroy

    respond_to do |format|
      format.html { redirect_to preferences_url }
      format.json { head :ok }
    end
  end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_form.html.erb
<%= form_for(@preference) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% @preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, '名前' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value, '値' %><br />
    <%= f.text_area :value, :rows => 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<h1>設定の編集<!-- Editing preference --></h1>

<%= render 'form' %>

<%= link_to '表示', @preference %> |
<%= link_to '一覧に戻る', preferences_path %>

app/views/preferences/index.html.erb
<h1>設定一覧<!-- Listing preferences --></h1>

<table class="preferences" >
  <tr>
    <th>名前<!-- Name --></th>
    <th>値<!-- Value --></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @preferences.each do |preference| %>
  <tr class="<%= cycle('list-line-odd', 'list-line-even') -%>" >
    <td><%= preference.name %></td>
    <td><%= preference.value %></td>
    <td><%= link_to '表示', preference %></td>
    <td><%= link_to '編集', edit_preference_path(preference) %></td>
    <td><%= link_to '削除', preference, confirm: '本当に削除してよろしいですか？', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '設定追加', new_preference_path %>

app/views/preferences/new.html.erb
<h1>設定の追加<!-- New preference --></h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', preferences_path %>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>名前<!-- Name -->:</b>
  <%= @preference.name %>
</p>

<p>
  <b>値<!-- Value -->:</b>
  <%= @preference.value %>
</p>


<%= link_to '編集', edit_preference_path(@preference) %> |
<%= link_to '一覧に戻る', preferences_path %>