config/routes.rb
Tapp01::Application.routes.draw do

	get "menuitems/index_tbody"
  resources :menuitems

  resources :releases

  match "names/absorb", :controller => :names, :action => :absorb
  match "names/delete_all", :controller => :names, :action => :delete_all
  match "names/export", :controller => :names, :action => :export, :via => :get
  match "names/import", :controller => :names, :action => :import

  resources :names

  resources :preferences

  get  "store/absorb_names"
  get  "store/check"
  get  "store/index"
  get  "store/new"
  get  "store/edit"
  match 'store/edit/:id', :controller => :store, :action => :edit
  post "store/cancel_order"
  post "store/deliver_order"
  post "store/save_order"
  get  "store/seimei"
  get  "store/show"
  match 'store/show/:id', :controller => :store, :action => :show
  get  "store/summary"
  get  "store/summary_table_by_date"

  resources :line_items

  resources :orders

  resources :products

  resources :titles

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweets Cafe | Premier</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "print/store.css", :media => 'print' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body onLoad="set_focus('order_id_to_edit');" onKeyUp="key_up(event);" >

<div id="columns" >
	<div id="side" >
		<div >
			<%= link_to "予約一覧", '/store/index' %>
		</div>
		<div >
			<%= link_to "新規予約", '/store/new' %>
		</div>
		<div class="spacer" >
		</div>
		<div >
			<label class="order_id_to_edit" 
				>予約番号</label><input id="order_id_to_edit" size="8" type="number" onFocus="this.select();" /><br/>
				<!--
				<%= form_tag '/store/show', :method => 'get' do %>
					<%= number_field_tag :id, params[:id], :class => 'number_field', :size => 8, :autocomplete => "off" -%><br/>
				<% end %>
				-->
			<%= link_to "表示印刷", '', :remote => true, :onClick => 'link_to_show();' -%><br/>
			<%= link_to "予約変更", '', :remote => true, :onClick => 'link_to_edit();' -%><br/>
		</div>
		<div class="spacer" >
		</div>
		<div >
			<%= link_to "予約集計", '/store/summary' %>
		</div>
		<div class="spacer" >
		</div>
		<div >
			<%= link_to "改訂管理", releases_path %>
		</div>
		<div >
			<%= link_to "品名管理", titles_path %>
		</div>
		<div >
			<%= link_to "商品管理", products_path %>
		</div>
		<div >
			<%= link_to "項目管理", menuitems_path %>
		</div>
		<div >
			<%= link_to "設定管理", preferences_path %>
		</div>
		<div >
			<%= link_to "予約管理", orders_path %>
		</div>
		<div >
			<%= link_to "詳細管理", line_items_path %>
		</div>
		<div >
		<% if Rails.env.production? %>
			<img src="/images/PremierLogoColor.png" alt="Premier Logo Color" />
		<% else %>
			<br/>
			<%= Rails.env -%>
		<% end %>
		</div>
	</div>
	<div id="main" >
<%= yield %>
	</div>
</div>

<script type="text/javascript" >
<!--
window.onunload = function () {};
history.forward();
-->
</script>
</body>
</html>